//embed{
    \includepdf[pages=1,fitpaper=true]{images/ads/01_grasys.pdf}
    \includepdf[pages=1,fitpaper=true]{images/ads/02_mediado.pdf}
    \includepdf[pages=1,fitpaper=true]{images/ads/03_sansan.pdf}
    \includepdf[pages=1,fitpaper=true]{images/ads/04_impressrd-pod.pdf}
    \includepdf[pages=1,fitpaper=true]{images/ads/05_impressrd-izumi.pdf}
    \includepdf[pages=1,fitpaper=true]{images/ads/06_technobrain.pdf}
    \includepdf[pages=1,fitpaper=true]{images/ads/07_graat.pdf}
//}
